### PR TITLE
Mix in JobHelpers directly

### PR DESCRIPTION
**Pull request by chefsalim**
This fixes https://github.com/chef/knife-push/issues/36

JobHelpers is now included directly into the Chef::Knife::JobStart class.  This allows the functions defined by Knife to be more accessible by the plug-in.

@lamont-granquist @thommay @tyler-ball @chef/client-core

### CODE REVIEW

**Comment by thommay** [comment]
I think this is a pretty big change in the API, and I'm not comfortable with it - and honestly, if we're saying that JobHelpers are just used in this one place, why not just put them straight in the class? 
I think I prefer adding the ability to pass the rest object into the JobHelper as an optional argument.

**Comment by chefsalim** [comment]
It's not just the rest usage. Trying to use other Knife methods fails as well. Passing in rest and any other methods we need doesn't seem like a great solution either...

/Users/salam/Workspace/knife-push/lib/chef/knife/job_helpers.rb:40:in `process_search': undefined local variable or method `ui' for Chef::Knife::JobHelpers:Module (NameError)

**Comment by lamont-granquist** [comment]
this is closer to how the code should have been written.  the module-with-all-the-class-methods pattern that it was using was definitely really bad.

i think i'm :+1: on this but you should bump the major verison to 1.0.0 before shipping.

**Comment by chefsalim** [comment]
Sounds good ... I'll bump up version to 1.0.0 in a separate PR (starting with a pre-release).

**Pull request merged**
