### PR TITLE
Use knife's rest method to ensure compatibility with all chef versions

### LINKED ISSUE #34: Broken on 12.7.2
```
INFO: Using configuration from /Users/scalp/.chef/knife.rb
/Users/scalp/.rvm/gems/ruby-2.2.4@chef/bundler/gems/knife-push-21bf51560993/lib/chef/knife/job_list.rb:24:in `run': uninitialized constant Chef::REST (NameError)
	from /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/chef-12.7.2/lib/chef/knife.rb:416:in `block in run_with_pretty_exceptions'
	from /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/chef-12.7.2/lib/chef/local_mode.rb:44:in `with_server_connectivity'
	from /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/chef-12.7.2/lib/chef/knife.rb:415:in `run_with_pretty_exceptions'
	from /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/chef-12.7.2/lib/chef/knife.rb:214:in `run'
	from /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/chef-12.7.2/lib/chef/application/knife.rb:148:in `run'
	from /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/chef-12.7.2/bin/knife:25:in `<top (required)>'
	from /Users/scalp/.rvm/gems/ruby-2.2.4@chef/bin/knife:22:in `load'
	from /Users/scalp/.rvm/gems/ruby-2.2.4@chef/bin/knife:22:in `<main>'
	from /Users/scalp/.rvm/gems/ruby-2.2.4@chef/bin/ruby_executable_hooks:15:in `eval'
	from /Users/scalp/.rvm/gems/ruby-2.2.4@chef/bin/ruby_executable_hooks:15:in `<main>'
```

cc @manderson26

### PR DESCRIPTION
**Pull request by martinisoft**
This changed in Chef 12.7 due to an API deprecation

Resolves #34

### CODE REVIEW

**Comment by coderanger** [comment]
I think the idea was to stop using `Chef::REST` entirely. /cc @thommay

**Comment by martinisoft** [comment]
@coderanger could be a re-factor later in another PR. This resolves the current issue at hand, but this particular change could break previous chef version compatibility too.

**Comment by martinisoft** [comment]
Added a rescue block to help with compatibility. Seems this issue goes a bit deeper into the actual push clients themselves in https://github.com/chef/opscode-pushy-client/pull/84

**Comment by thommay** [comment]
there's already a `rest` method in Chef::Knife that will do the right thing; the correct fix here, and one that will work for all of time, is to simply stop creating a new `rest` instance and use the one provided.

**Comment by thommay** [comment]
so I'm :-1: on this change as it stands, we're just creating work for ourselves down the line.

**Comment by martinisoft** [comment]
@thommay Any guidence on where to look for that API then? As it stands push-jobs client and server are broken across ChefDK 0.11.0, Chef Server 12.4.1, and Chef Client 12.7.2

**Comment by thommay** [comment]
delete all the lines like `rest = Chef::REST.new(Chef::Config[:chef_server_url])`, and it should just work.

**Comment by martinisoft** [comment]
@thommay Even for older Chef clients?

**Comment by thommay** [comment]
@martinisoft yeah, all the way back to Chef 0.9 at least

**Comment by martinisoft** [comment]
@thommay All corrected :+1:

**Comment by thommay** [comment]
you shouldn't need the imports either…

**Comment by martinisoft** [comment]
@thommay Done :+1:

**Comment by thommay** [comment]
:+1: LGTM, thanks!

**Comment by martinisoft** [comment]
Cleaned up the white spacing so the change set is cleaner and smaller.

**Comment by stevendanna** [comment]
:+1: Good solution, thanks for taking the time to sort this out @martinisoft

**Comment by tyler-ball** [comment]
:+1:

**Comment by cheeseplus** [comment]
:+1:

**Comment by lamont-granquist** [comment]
:+1:

**Comment by martinisoft** [comment]
@stevendanna Welcome! Would love to see this and the related issues merged because we're currently unable to use Chef Push Jobs at all with ChefDK 0.11, Chef Server 12.4.1, and Chef Client 12.7.2 :cry:

**Comment by scalp42** [comment]
@thommay I think this is still broken:

```
/Users/scalp/.rvm/gems/ruby-2.2.4@chef/bundler/gems/knife-push-e295f1e87927/lib/chef/knife/job_helpers.rb:97:in `run_helper': undefined local variable or method `rest' for Chef::Knife::JobHelpers:Module (NameError)
	from /Users/scalp/.rvm/gems/ruby-2.2.4@chef/bundler/gems/knife-push-e295f1e87927/lib/chef/knife/job_start.rb:106:in `run'
	from /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/chef-12.8.1/lib/chef/knife.rb:421:in `block in run_with_pretty_exceptions'
	from /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/chef-12.8.1/lib/chef/local_mode.rb:44:in `with_server_connectivity'
	from /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/chef-12.8.1/lib/chef/knife.rb:420:in `run_with_pretty_exceptions'
	from /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/chef-12.8.1/lib/chef/knife.rb:219:in `run'
	from /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/chef-12.8.1/lib/chef/application/knife.rb:148:in `run'
	from /Users/scalp/.rvm/gems/ruby-2.2.4@chef/gems/chef-12.8.1/bin/knife:25:in `<top (required)>'
	from /Users/scalp/.rvm/gems/ruby-2.2.4@chef/bin/knife:22:in `load'
	from /Users/scalp/.rvm/gems/ruby-2.2.4@chef/bin/knife:22:in `<main>'
	from /Users/scalp/.rvm/gems/ruby-2.2.4@global/bin/ruby_executable_hooks:15:in `eval'
	from /Users/scalp/.rvm/gems/ruby-2.2.4@global/bin/ruby_executable_hooks:15:in `<main>'
```

```
$> bundle show | egrep "chef \(|knife-push"
  * chef (12.8.1)
  * knife-push (0.9.1 e295f1e)
```

**Comment by martinisoft** [comment]
@scalp42 Can you try this with 12.7.2 and re-test? I'm wondering if 12.8.1 introduced a regression there.

**Comment by stevendanna** [comment]
I think the issue is that JobHelper is used via module methods rather than being mixed into the knife command's class so it doesn't have access to the `rest` method.

**Comment by scalp42** [comment]
@martinisoft trying right now with 12.7.2

Will report.

**Comment by scalp42** [comment]
@martinisoft @stevendanna 

```
scalp@mbp42:~/chef (*)>  bundle show | egrep "chef \(|knife-push"
  * chef (12.7.2)
  * knife-push (0.9.1 e295f1e)

scalp@mbp42:~/chef (*)> bundle exec knife job list | tail
run_timeout: 1200
status:      complete
updated_at:  Sun, 13 Mar 2016 07:19:41 GMT

command:     apt-purge
created_at:  Sun, 13 Mar 2016 21:34:17 GMT
id:          7d5743956007883752a3bfcb09470580
run_timeout: 30000
status:      complete
updated_at:  Sun, 13 Mar 2016 21:34:25 GMT

scalp@mbp42:~/chef (*)> bundle exec knife job start apt-purge -s 'chef_environment:*' --timeout  30000 --quorum 1%
ERROR: knife encountered an unexpected error
This may be a bug in the 'job start' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a bug report.
Exception: NameError: undefined local variable or method `rest' for Chef::Knife::JobHelpers:Module
```

**Comment by martinisoft** [comment]
So that is probably related to #36 then, what do you think @stevendanna and @thommay ?

**Comment by UnbounDev** [comment]
Can confirm this is still an issue, any headway on it (error report below)?

Getting an undefined `rest` error for me using a fresh install of the ChefDK and fresh install of knife-push

```
INFO: Using configuration from /Users/austin/chef/chef-repo/.chef/knife.rb
/Users/austin/.chefdk/gem/ruby/2.1.0/gems/knife-push-0.9.1/lib/chef/knife/job_helpers.rb:95:in `run_helper': undefined local variable or method `rest' for Chef::Knife::JobHelpers:Module (NameError)
	from /Users/austin/.chefdk/gem/ruby/2.1.0/gems/knife-push-0.9.1/lib/chef/knife/job_start.rb:106:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/knife.rb:416:in `block in run_with_pretty_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/local_mode.rb:44:in `with_server_connectivity'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/knife.rb:415:in `run_with_pretty_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/knife.rb:214:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application/knife.rb:148:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/bin/knife:25:in `<top (required)>'
	from /opt/chefdk/bin/knife:50:in `load'
	from /opt/chefdk/bin/knife:50:in `<main>'
```

knife-push:
```
$ gem list | grep knife-push
knife-push (0.9.1)
```

ChefDk:
```
$ chef -v
Chef Development Kit Version: 0.11.2
chef-client version: 12.7.2
berks version: 4.2.0
kitchen version: 1.5.0

$ knife -v
Chef: 12.7.2
```

ChefDk packaged ruby:
```
$ which ruby
/opt/chefdk/embedded/bin/ruby
$ ruby -v
ruby 2.1.6p336 (2015-04-13 revision 50298) [x86_64-darwin12.0]
```

**Comment by lamont-granquist** [comment]
#36 is the bug report on this issue, stop responding to a closed+merged PR

**Pull request merged**
